version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${PORT}:${PORT}
    networks:
      - nodejs2022q2-network
    restart: always
    volumes:
        - .:/app/  
        - /app/node_modules 
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - nodejs2022q2-network
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log

  dbadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${DB_ADMIN_PORT_DOCKER}:${DB_ADMIN_PORT_DOCKER_ADDITIONAL}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  db_data:
  db_logs:

networks:
 nodejs2022q2-network:
    driver: bridge 
